---
- name: Add fwpp repo {{ repo_url }}
  ansible.builtin.yum_repository:
    name: fwpp
    description: Firmware Pack for ProLiant
    baseurl: "{{ repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ repo_gpg_key }}"
  tags: repo

- name: Install packages
  ansible.builtin.include_tasks: RedHat-install-package.yml
  loop: "{{ hpe_fwpp_packages }}"
  loop_control:
    loop_var: pkg
  when: hpe_fwpp_packages is defined
  tags: packages
